import Head from "next/head";
import Container from "react-bootstrap/Container";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Card from "../components/Card";
import Col from "react-bootstrap/Col";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container fluid="xxl" as="main" className="py-4 px-3 mx-auto">
        <Header />
        <Col lg={6} className="px-0">
          <Card />
        </Col>
        <Footer />
      </Container>
    </>
  );
}
